spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chalermphan172
    password: khumrvqwcesjsmwa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
---
app:
  token:
    secret: m#MySecret02222
    issuer: BackendService
  email:
    from: YOUR_ACCOUNT@gmail.com

